apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns-solver-ifeswcom
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/http2-max-header-size: "50m"
    nginx.ingress.kubernetes.io/http2-max-field-size: "50m"
    nginx.ingress.kubernetes.io/server-snippet: | # for large header accepted
      large_client_header_buffers 4 50m;
      http2_max_header_size 50m;
      http2_max_field_size 50m;
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-{{ .Chart.Name }}
    app.kubernetes.io/version: 1.1.0
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.app.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Chart.Name }}-dagster-dagit-service
                port:
                  number: 3000
            path: /
            pathType: Prefix
