apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-dagster-dagit-service
spec:
  type: NodePort
  selector:
    app: {{ .Chart.Name }}-dagster-dagit
  ports:
    - protocol: TCP
      port: {{ .Values.docker.backend.port }}
      targetPort: {{ .Values.docker.backend.targetPort }}
      nodePort: 30200