apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Chart.Name }}-secret-provider-class
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.app.secretCSIDriver.clientID }}
    keyvaultName: {{ .Values.app.keyvaultName }}
    objects:  | 
      array:
        - |
          objectName: <dockerPullSecretObjectName>
          objectType: secret
        - |
          objectName: <dbHostObjectName>
          objectType: secret
        - |
          objectName: <dbUserObjectName>
          objectType: secret
        - |
          objectName: <dbPasswordObjectName>
          objectType: secret
    tenantId: {{ .Values.app.tenantID }}
  secretObjects:
    - data:
      - key: .dockerconfigjson
        objectName: <dockerPullSecretObjectName>
      secretName: azure-pull-secret
      type: kubernetes.io/dockerconfigjson
    - data:
      - key: <dbHostObjectName>
        objectName: <dbHostObjectName>
      secretName: db-host-secret
      type: Opaque
    - data:
      - key: <dbUserObjectName>
        objectName: <dbUserObjectName>
      secretName: db-user-secret
      type: Opaque
    - data:
      - key: <dbPasswordObjectName>
        objectName: <dbPasswordObjectName>
      secretName: db-password-secret
      type: Opaque